config/routes.rb
Rails.application.routes.draw do

  resources :boards do
    resources :comments
  end

  get 'boards/new/:lat/:lng' => 'boards#new', :format => false, :lat => /.*/, :lng => /.*/
  get 'boards/getNearby/:lat/:lng' => 'boards#getNearby', :format => false, :lat => /.*/, :lng => /.*/
  get 'boards/detail/:id' => 'boards#detail'
  get 'boards/sendFeedback/:id/:gb/:ud' => 'boards#sendFeedback'

  root :to => 'boards#index'

end

app/models/board.rb
# coding: utf-8
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  # attr_accessible :image # モデルではなく，コントローラでパラメータをフィルタリングする

  # mount_uploader :image, ImageUploader
  mount_base64_uploader :image, ImageUploader


  enum back_type: %i(/assets/minisign_b.png /assets/minisign_y.png /assets/minisign_r.png)
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :board

  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :boards
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
# coding: utf-8
class BoardsController < ApplicationController
  include CarrierwaveBase64Uploader
  before_action :set_board, only: [:show, :edit, :update, :destroy]

	# GET /
	def index
    @boards = Board.all
		@board = Board.new
    render
	end

	# GET /boards/getNearbyBoards/:lat/:lng
  # 周辺標識のAPI
	def getNearby
    c = Board.arel_table
    # res = Board.where(c[:latitude].gt(30)
    #                    .and(c[:latitude].lt(50))
    #                    .and(c[:longitude].gt(130))
    #                    .and(c[:longitude].lt(150)))
    #       .select(c[:id])
    #       .select(c[:back_type])
    #       .select(c[:latitude])
    #       .select(c[:longitude])
    #       .to_json
    res = Board.all.to_json

    render :json => res
  end

  # GET /boards/detail/:id
  # 標識詳細のAPI
  def detail
    c = Board.arel_table
    res = Board.find(params[:id]).to_json

    render :json => res
  end

  # GET /boards/:id
  # 標識詳細のAPI
  # def show
  # 	c = Board.arel_table
  #   res = Board.find(params[:id]).to_json

  # 	render :json => res
  # end

  # GET /boards/:id
  # GET /boards/:id.json
  def show
    # respond_to do |format|
    #   format.html
    #   format.json { render json: @board }
    # end

    # gem jbuilder を使う
    # http://railscasts.com/episodes/320-jbuilder?language=ja&view=asciicast
  end


  # GET /boards/sendFeedback/:id/:gb/:ud
  # Good と Badをインクリメント、デクリメントするAPI
  # (g => good, b => bad), (u => up, d => down)
  def sendFeedback
    if params[:gb] == 0
      if params[:ud] == 0
        Board.find(params[:id]).increment(:good).save
      elsif params[:ud] == 1
        Board.fill(params[:id]).decrement(:good).save
      end
    elsif params[:gb] == 1
      if params[:ud] == 0
        Board.find(params[:id]).increment(:bad).save
      elsif params[:ud] == 1
        Board.fill(params[:id]).decrement(:bad).save
      end
    end
  end


  # GET /boards/new/:lat/:lng
  def new
    @board = Board.new
    @lat = params[:lat]
    @lng = params[:lng]
  end

  # GET /users/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  # def create
  #   #@board = Board.new(params[:id])
  #   @board = Board.new(board_params)

  #   respond_to do |format|
  #     if @board.save
  #       format.html { redirect_to @board, notice: 'Board created' }
  #       format.json { render :show, status: :created, location: @board }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @board.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # POST /boards
  # POST /boards.json
  def create
    tmp_board_params = board_params
    image_data = base64_conversion(tmp_board_params[:remote_image_url])
    tmp_board_params[:image] = image_data
    tmp_board_params[:remote_image_url] = nil
    tmp_board_params[:good] = 0
    tmp_board_params[:bad] = 0

    @board = Board.new(tmp_board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board created' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    # redirect_to edit_board_path(@board)
    end
  end

  # PATCH/PUT /boards/:id
  # PATCH/PUT /boards/:id.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board updated' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /boards/:id
  # DELETE /boards/:id.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board destroyed' }
      format.json { head :no_content }
    end
  end

  private
  def set_board
    @board = Board.find(params[:id])
  end

  # モデルではなくコントローラでパラメータのフィルタリングをする．
  def board_params
    params.require(:board).permit(:caption, :latitude, :longitude, :back_type, :good, :bad, :image, :remove_image, :image_cache, :remote_image_url) # マイグレーションファイルの確認をせよ．:user は userモデルへの参照型なので，ここで指定するとerrorとなる？
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #POST /boards/:board_id/comments
  def create
    @board = Board.find(params[:board_id])
    @comment = @board.comments.create(comment_params)

    logger.debug "@board"
    logger.debug "params"
    #redirect_to board_path(@board)
    redirect_to "/boards#index"
  end

  #DELETE /boards/:board_id/comments/:id
  def destroy
    @board = Board.find(params[:board_id])
    @comment = @board.comments.find(params[:id])
    @comment.destroy

    redirect_to board_path(@board)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/concerns/carrierwave_base64_uploader.rb
module CarrierwaveBase64Uploader
  extend ActiveSupport::Concern

  private

  def base64_conversion(uri_str, filename = 'base64')
    image_data = split_base64(uri_str)
    image_data_string = image_data[:data]
    image_data_binary = Base64.decode64(image_data_string)

    temp_img_file = Tempfile.new(filename)
    temp_img_file.binmode
    temp_img_file << image_data_binary
    temp_img_file.rewind

    img_params = {:filename => "#{filename}.#{image_data[:extension]}", :type => image_data[:type], :tempfile => temp_img_file}
    ActionDispatch::Http::UploadedFile.new(img_params)
  end

  def split_base64(uri_str)
    if uri_str.match(%r{data:(.*?);(.*?),(.*)$})
      uri = Hash.new
      uri[:type] = $1
      uri[:encoder] = $2
      uri[:data] = $3
      uri[:extension] = $1.split('/')[1]
      return uri
    else
      return nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% @board.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <p>
      <%= image_tag(@board.image_url(:thumbnail), :width => 80, :height => 80) %>
      <%= f.file_field :image %>
    </p>

    <p>
      <%= f.label :remote_image_url, "base64 format" %>
      <%= f.text_field :remote_image_url, placeholder: "http://hogehoge..." %>
    </p>

    <p>
      <%= f.label :caption %>
      <%= f.text_field :caption , placeholder: "うんこ落ちてる" %>
    </p>

    <p>
      <%= f.check_box :remove_image %> 画像削除
      <%= f.hidden_field :image_cache %>
    </p>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', board_path %>

app/views/boards/index.html.erb
<%= javascript_include_tag "https://maps-api-ssl.google.com/maps/api/js?v=3&sensor=false", "boards/map.js", "boards/jquery.fullPage.min.js", "boards/jquery.flip.min.js", "boards/init.js" %>
<%= stylesheet_link_tag "boards.css", "jquery.fullPage.css" %>

<div id="fullpage">
	<div class="section">
		<div id="map"></div>
		<a href=""><img src="/assets/UI-build.png" alt="BUILD" id="build-button"></a>
	</div>
	<div class="section">


		<div class="flipper">

			<div class="front">

				<div id="hyoushiki">

					<span id="return-button"><a href="#m"><img src="/assets/UI-return.png" width="60"/></a></span>

					<div id="haikei"><img src="/assets/UI-ura-cloud.png" width="360"/></div>


					<div id="hyoushiki-img-1"><img src="/assets/UI-kanban-dummy.png" width="250" class="board-img"/></div>


					<div id="hyoushiki-img-2"><img src="/assets/UI-kanban-2.png" width="250" /></div>

					<div id="caption">
						<p class="board-caption"><%= @board.caption %></p>
					</div>


					<div id="hyouka">
						<img src="/assets/UI-info-back.png" width="150"/>
					</div>

					<div id="hyouka-button-set">

						<span class="counter" id="good-count">23</span>
						<span id="good-button">
						  <a href="#"><img src="/assets/UI-info-like.png" width="60" /></a>

						</span>
						<span id="bad-button">
							<a href="#"><img src="/assets/UI-info-unlike.png" width="60" /></a>
						</span>
						<span class="counter" id="bad-count">23</span>


					</div>

					<div id="social-button-set">
						<span ><img src="/assets/UI-facebook.png" width="50" ></span>
						<span ><img src="/assets/UI-twitter.png" width="50" ></span>
						<span ><img src="/assets/UI-google.png" width="50" /></span>
					</div>



				</div>

			</div>
			<div class="back">

				<div id="ura-hyoushiki">

					<span id="ura-return-button"><a href="#m"><img src="/assets/UI-return.png" width="60"/></a></span>

					<div id="ura-haikei"><img src="/assets/UI-ura-cloud.png" width="360"/></div>

					<div class="metainfo">
						もうせ</br>
						<span id="created-at">2015-9-18</span>d
					</div>



					<div id="ura-hyoushiki-img-1"><img src="/assets/UI-kanban-dummy.png" width="150" class="board-img"/></div>

					<div id="ura-hyoushiki-img-2"><img src="/assets/UI-kanban-2.png" width="150" /></div>

					<div id="ura-caption">
						<p class="board-caption"><%= @board.caption %></p>
					</div>


          <div class="comment">
            <div class="comment-body">
							面白い!
						</div>
						<div class="comment-foot">
							名無しさん
						</div>
						<hr>
						<div class="comment-body">
							最高!
						</div>
						<div class="comment-foot">
							もうせ
						</div>
						<hr>

            <div id="displaycomment"></div>
            <div id="username"></div>
          </div>

					<div class="addcomment">

            <input type="text" maxlength='15' id="inputcomment">
            <button onclick="comment()">投稿</button>
					</div>



        </div>

      </div><!--back-->
    </div><!--flipper-->

  </div>
</div>

app/views/boards/new.erb
<%= javascript_include_tag "new/jquery-migrate-1.2.1.min.js", "new/jquery-ui.js", "slick/slick.min.js" %>
<%= stylesheet_link_tag "new.css", "slick.css", "slick-theme.css" %>

<span id="latitude" ><%= @lat %></span>
<span id="longitude" ><%= @lng %></span>


<div id="canvas">
  <canvas id="canvasElement" width="400" height="400"></canvas>
</div>
<div id = "select" >
  <div class="center">


    <!-- <form action="/users" class="new_user" id="new_user" method="post"> </form> -->
    <input type="text" id="caption" maxlength='12'/>


    <!-- ここをgetで値を取って、関数を呼び出してください。 -->
    <button onclick="change_board(1)">‎<img class="imgboard" src="/assets/board/blue.png" height="50" width="50"></button>
    <button onclick="change_board(2)"><img class="imgboard" src="/assets/board/yellow.png" height="50" width="50"></button>
    <button onclick="change_board(3)"><img class="imgboard" src="/assets/board/red.png" height="50" width="50"></button>

    <div id="tabs">

      <div id="tabs-1">
        <div class="signselector">
          <div><button onclick="stamp('left', 'none')"><img src="/assets/grayIcon/left/none.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'ame')"><img src="/assets/grayIcon/left/ame.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'car')"><img src="/assets/grayIcon/left/car.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'cat')"><img src="/assets/grayIcon/left/cat.png" height="80" width="80"></button> </div>
          <div><button onclick="stamp('left', 'karaoke')"><img src="/assets/grayIcon/left/karaoke.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'kisskidf')"><img src="/assets/grayIcon/left/kisskidf.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'kisskidm')"><img src="/assets/grayIcon/left/kisskidm.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'man')"><img src="/assets/grayIcon/left/man.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'motituki')"><img src="/assets/grayIcon/left/motituki.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'nozoki')"><img src="/assets/grayIcon/left/nozoki.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'panda')"><img src="/assets/grayIcon/left/panda.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'run')"><img src="/assets/grayIcon/left/run.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'samurai')"><img src="/assets/grayIcon/left/samurai.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'syagamu')"><img src="/assets/grayIcon/left/syagamu.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'tomb')"><img src="/assets/grayIcon/left/tomb.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'woman')"><img src="/assets/grayIcon/left/woman.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'youjo')"><img src="/assets/grayIcon/left/youjo.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('left', 'hamburger')"><img src="/assets/grayIcon/left/hamburger.png" height="80" width="80"></button></div>
        </div>
      </div>
      <div id="tabs-2">
        <div class="signselector">
          <div><button onclick="stamp('center', 'none')"><img src="/assets/grayIcon/center/none.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('center', 'banzai')"><img src="/assets/grayIcon/center/banzai.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('center', 'barerina')"><img src="/assets/grayIcon/center/barerina.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('center', 'chair')"><img src="/assets/grayIcon/center/chair.png" height="80" width="80"></button> </div>
          <div><button onclick="stamp('center', 'heart')"><img src="/assets/grayIcon/center/heart.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('center', 'lead')"><img src="/assets/grayIcon/center/lead.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('center', 'nessi')"><img src="/assets/grayIcon/center/nessi.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('center', 'ochai')"><img src="/assets/grayIcon/center/ochai.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('center', 'skul')"><img src="/assets/grayIcon/center/skul.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('center', 'unko')"><img src="/assets/grayIcon/center/unko.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('center', 'ushi')"><img src="/assets/grayIcon/center/ushi.png" height="80" width="80"></button></div>
        </div>
      </div>
      <div id="tabs-3">
        <div class="signselector">
          <div><button onclick="stamp('right', 'none')"><img src="/assets/grayIcon/right/none.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'nukarumi')"><img src="/assets/grayIcon/right/nukarumi.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'car')"><img src="/assets/grayIcon/right/car.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'cat')"><img src="/assets/grayIcon/right/cat.png" height="80" width="80"></button> </div>
          <div><button onclick="stamp('right', 'karaoke')"><img src="/assets/grayIcon/right/karaoke.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'kisskidf')"><img src="/assets/grayIcon/right/kisskidf.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'kisskidm')"><img src="/assets/grayIcon/right/kisskidm.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'man')"><img src="/assets/grayIcon/right/man.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'motituki')"><img src="/assets/grayIcon/right/motituki.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'nozoki')"><img src="/assets/grayIcon/right/nozoki.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'panda')"><img src="/assets/grayIcon/right/panda.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'run')"><img src="/assets/grayIcon/right/run.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'samurai')"><img src="/assets/grayIcon/right/samurai.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'syagamu')"><img src="/assets/grayIcon/right/syagamu.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'tomb')"><img src="/assets/grayIcon/right/tomb.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'woman')"><img src="/assets/grayIcon/right/woman.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'youjo')"><img src="/assets/grayIcon/right/youjo.png" height="80" width="80"></button></div>
          <div><button onclick="stamp('right', 'hamburger')"><img src="/assets/grayIcon/right/hamburger.png" height="80" width="80"></button></div>
        </div>
      </div>
      <ul>
        <li><a href="#tabs-1"><img src="/assets/signal_left_h.png" width="60" id="blue"></a></li>
        <li><a href="#tabs-2"><img src="/assets/signal_center_def.png" width="45" id="yellow"></a></li>
        <li><a href="#tabs-3"><img src="/assets/signal_right_def.png" width="60" id="red"></a></li>
      </ul>
    </div>
    <!-- <div onclick="build()"><img src="/assets/UI parts/UI-make-build.png" width="80"></div> -->

    <%= form_for(@board) do |f| %>
      <%= f.hidden_field :remote_image_url %>
      <%= f.hidden_field :caption %>
      <%= f.hidden_field :latitude %>
      <%= f.hidden_field :longitude %>
      <%= f.hidden_field :back_type %>
      <div class="actions">
        <div id="canvas_output">
          <button name="button" type="submit"><img src="/assets/UI parts/UI-make-build.png" width="80"></button>
        </div>
      </div>
    <% end %>
  </div>

  <img id="newImg">

</div>


<%= javascript_include_tag "new/pngExpoter.js" %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/new.html_old.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/new2.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User Name:</b>
  <%= @board.user %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag(@board.image_url) %>
</p>

<h2>Comments</h2>
<%= render @board.comments %>

<h2>Add Comment</h2>
<%= render "comments/form" %>


<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/comments/_comment.html.erb
<div class="comment-body">
	<%= simple_format comment.body %>
</div>
<div class="comment-foot">
	名無しさん
</div>
<p>
  <%= link_to 'Destroy a Comment', [comment.board, comment], method: :delete, data: { confirm: 'Are you sure destroy a comment?' } %>
</p>
<hr>

app/views/comments/_form.html.erb
<%= form_for( [@board, @board.comments.build] ) do |f| %>
  <p>
    <%= f.label :body, "Comment" %><br />
    <%= f.text_area :body, cols: 40, rows: 4 %>
  </p>

  <p>
    <%= f.submit "Add Comment" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bom</title>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>